export const transactions = [
  {
    id: 1,
    name: "Internet Bill",
    category: "Utilities",
    dateTime: "2028-03-05 10:15:23",
    amount: 120.5,
    status: "Completed",
    note: "Monthly broadband subscription",
  },
  {
    id: 2,
    name: "Grocery Shopping",
    category: "Shopping",
    dateTime: "2028-03-07 15:47:11",
    amount: 185.75,
    status: "Completed",
    note: "Weekly groceries at supermarket",
  },
  {
    id: 3,
    name: "Concert Tickets",
    category: "Entertainment",
    dateTime: "2028-02-28 20:05:42",
    amount: 310,
    status: "Failed",
    note: "Tickets for live music concert",
  },
  {
    id: 4,
    name: "Pharmacy Purchase",
    category: "Healthcare",
    dateTime: "2028-02-10 12:22:54",
    amount: 75.9,
    status: "Completed",
    note: "Medicines and health supplements",
  },
  {
    id: 5,
    name: "Family Dinner",
    category: "Dining Out",
    dateTime: "2028-02-15 19:36:09",
    amount: 240.6,
    status: "Pending",
    note: "Dinner with family at Thai restaurant",
  },
];
